### ISSUE TITLE
stack_rm asks for confirmation and CI fails

### ISSUE THREAD

**Issue by kenfdev** [pulumi/circleci#21]
I've tried to use the `stack_rm` orb but it failed to remove the stack because it asks for confirmation like the following:

![image](https://user-images.githubusercontent.com/3941889/67100408-92e35200-f1fa-11e9-9202-707b8cbb954b.png)

The `force` option doesn't work either.

I've added the `--yes` option and it succeeded. I remember discussing about this in the comment here:

https://github.com/pulumi/circleci/pull/14#discussion_r331820864

Is this the `pulumi` CLI's problem?

**Comment by pgavlin** [comment]
cc @chrsmith

**Comment by chrsmith** [comment]
> Is this the pulumi CLI's problem?

Yes, I believe this is a bug in `pulumi`. For the time being, let's keep this issue open and we can work around the issue by passing `--yes` like you mentioned. But I'll follow up and see what the expected behavior should be here. As my understanding was that all confirmation prompts were skipped if running in a non-interactive session (e.g. a CI/CD job).
